services:
  immichalbumdownloader:
    image: jwestfalewski/immich-album-downloader:1.0.0
    user: 1001:1001
    environment:
      NODE_ENV: production
      IMMICH_HOST: 'http://127.0.0.1:2283/'
      IMMICH_APIKEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      ALBUM_ID: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
      ALBUM_OUTPUT_PATH: '/album'
      CRON_TIME: '0 * * * * *'
      TZ: 'Europe/Warsaw'
    volumes:
      - ./test:/album:rw
